apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmdetails-deployment
spec:
  selector:
    matchLabels:
      app: cmdetails
      version: v1
  replicas: 3
  template:
    metadata:
      labels:
        app: cmdetails
        version: v1
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: cmdetails-container
        image: dazzabiggs/kb-cmind-api-cmdetails:1.2.0
        ports:
        - containerPort: 80
      